apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::051674313773:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-wq0ZhTJgNTLy
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::051674313773:user/suresh
      username: suresh
    - groups:
        - roboshop-trainee
        userarn: arn:aws:iam::051674313773:user/john
        username: john
    - groups
      - roboshop-trainee
      userarn: arn:aws:iam::051674313773:user/sreeram
      username: sreeram
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::051674313773:user/ramesh
      username: ramesh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-15T06:18:14Z"
  name: aws-auth
  namespace: kube-system
  uid: b0acfeca-2f4c-4b60-8d9b-e80c6d53f87f

