apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::051674313773:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-wq0ZhTJgNTLy
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn:arn:aws:iam::051674313773:user/suresh
      username:suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-15T06:18:14Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1126"
  uid: 749e9d29-4c96-4d35-9cd1-a179e5b3b392
