apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::051674313773:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-wq0ZhTJgNTLy
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::051674313773:user/suresh
      username: suresh
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::051674313773:user/john
      username: john
    - groups
      - roboshop-trainee
      userarn: arn:aws:iam::051674313773:user/sreeram
      username: sreeram
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::051674313773:user/ramesh
      username: ramesh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-15T06:18:14Z"
  name: aws-auth
  namespace: kube-system
  uid: 9ea480c4-476a-41fa-881a-9a6ef28eefc2


